// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/mdc-dark-deeppurple/theme.css';
import 'primeicons/primeicons.css';
// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <PrimeReactProvider>
      <html lang='en'>
        <body
          style={{
            margin: 0,
            display: 'flex',
            justifyContent: 'center',
          }}>
          {children}
        </body>
      </html>
    </PrimeReactProvider>
  );
}
