// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/soho-dark/theme.css';
import 'primeicons/primeicons.css';
import { _apiCall } from './utils/helpers/functions';
// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  return (
    <PrimeReactProvider>
      <html lang='en'>
        <body
          style={{
            display: 'flex',
            justifyContent: 'center',
            overflow: 'hidden',
          }}>
          <div
            style={{
              maxWidth: 1550,
              width: '100%',
            }}>
            {children}
          </div>
        </body>
      </html>
    </PrimeReactProvider>
  );
}
